name: 'Your name here'
description: 'Sets version info for a project by using git tags'
author: 'FacilityNet'
outputs:
  full:
    description: 'The full version'
  major:
    description: 'The major version'
  minor:
    description: 'The minor version'
  patch:
    description: 'The patch version'
  preRelease:
    description: 'The pre-release component, if any'
  buildMetadata:
    description: 'The build metadata component, if any'
runs:
  using: 'node12'
  main: 'dist/index.js'
