name: "test"
on: # only run integration test for release branches
  pull_request:
  push:
    branches:
      - 'releases/*'

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        eventName: 'push'
